"""scripts/brew_formula.py: the Homebrew formula generated from uv.lock (#95). Offline: a
fixture lock, the checkout's own uv.lock and a fake sdist; nothing is downloaded."""

import hashlib
import importlib.util
import re
import sys
import tomllib
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pytest

REPO = Path(__file__).resolve().parents[1]
_SCRIPT = REPO / "scripts" / "brew_formula.py"
if TYPE_CHECKING:
    import brew_formula as brew
else:
    _spec = importlib.util.spec_from_file_location("brew_formula", _SCRIPT)
    assert _spec
    assert _spec.loader
    brew = importlib.util.module_from_spec(_spec)
    # @dataclass resolves annotations through sys.modules, so register before executing.
    sys.modules["brew_formula"] = brew
    _spec.loader.exec_module(brew)

SHA = "a" * 64


def _pkg(
    name: str, version: str, deps: str = "", sdist: bool = True, extra_tables: str = ""
) -> str:
    digest = hashlib.sha256(name.encode()).hexdigest()
    lines = [
        "[[package]]",
        f'name = "{name}"',
        f'version = "{version}"',
        'source = { registry = "https://pypi.org/simple" }',
    ]
    if deps:
        lines.append(f"dependencies = [{deps}]")
    if sdist:
        url = f"https://files.pythonhosted.org/packages/xx/{name}-{version}.tar.gz"
        lines.append(f'sdist = {{ url = "{url}", hash = "sha256:{digest}", size = 1 }}')
    return "\n".join(lines) + "\n" + extra_tables + "\n"


LOCK = (
    'version = 1\nrevision = 3\nrequires-python = ">=3.12"\n\n'
    + _pkg(
        "promptmend",
        "1.2.0",
        '{ name = "httpx", extra = ["socks"] }, { name = "Typer" }, '
        '{ name = "macos-only", marker = "sys_platform == \'darwin\'" }, '
        "{ name = \"linux-only\", marker = \"platform_system == 'Linux' and os_name == 'posix'\" }",
        sdist=False,
        extra_tables='[package.dev-dependencies]\ndev = [{ name = "pytest" }]\n',
    ).replace('source = { registry = "https://pypi.org/simple" }', 'source = { editable = "." }')
    + _pkg(
        "httpx",
        "0.28.1",
        '{ name = "anyio" }',
        extra_tables='[package.optional-dependencies]\nsocks = [{ name = "socksio" }]\n'
        'http2 = [{ name = "h2" }]\n',
    )
    + _pkg(
        "anyio",
        "4.0.0",
        '{ name = "typing-extensions", marker = "python_full_version < \'3.13\'" }, '
        '{ name = "idna" }',
    )
    + _pkg("idna", "3.10")
    + _pkg("socksio", "1.0.0")
    + _pkg("h2", "4.0.0")
    + _pkg("typing-extensions", "4.12.2")
    + _pkg(
        "typer",
        "0.12.0",
        '{ name = "colorama", marker = "sys_platform == \'win32\'" }, '
        "{ name = \"rich\", marker = \"extra == 'all' or python_version >= '3.8'\" }",
    )
    + _pkg("colorama", "0.4.6")
    + _pkg("rich", "13.0.0")
    + _pkg("macos-only", "1.0")
    + _pkg("linux-only", "2.0")
    + _pkg("pytest", "9.0.0")
)


def _lock(text: str = LOCK) -> dict[str, Any]:
    return tomllib.loads(text)


def _render(lock: dict[str, Any] | None = None, **kw: str) -> str:
    args = {"version": "1.2.0", "sdist_url": brew.sdist_url("1.2.0"), "sdist_sha256": SHA}
    args |= {"python": "3.14", **kw}
    return brew.render(_lock() if lock is None else lock, **args)


def _resources(text: str) -> list[str]:
    return re.findall(r'resource "([^"]+)" do', text)


def _names(lock: dict[str, Any], env: dict[str, str]) -> set[str]:
    return {name for name, _ in brew.runtime_packages(lock, env)}


def test_runtime_packages_follow_markers_and_extras() -> None:
    envs = brew.environments("3.14")
    assert _names(_lock(), envs["macos"]) == {
        "httpx", "anyio", "idna", "socksio", "typer", "rich", "macos-only",
    }  # fmt: skip
    assert ("linux-only", "2.0") in brew.runtime_packages(_lock(), envs["linux"])
    # typing-extensions only below 3.13; never the dev group, h2 (an extra not asked for) or
    # colorama (Windows only).
    assert "typing-extensions" in _names(_lock(), brew.environments("3.12")["linux"])


def test_formula_text() -> None:
    text = _render()
    assert text.startswith("# Generated by scripts/brew_formula.py")
    assert "class PromptWorkflow < Formula\n  include Language::Python::Virtualenv\n" in text
    assert f'  url "{brew.REPO_URL}/releases/download/v1.2.0/' in text
    assert "promptmend-1.2.0.tar.gz" in text
    assert f'  sha256 "{SHA}"' in text
    assert '  depends_on "python@3.14"' in text
    assert "    virtualenv_install_with_resources\n" in text
    assert _resources(text) == [
        "anyio", "httpx", "idna", "rich", "socksio", "typer",  # both platforms, sorted
        "macos-only",  # on_macos
        "linux-only",  # on_linux
    ]  # fmt: skip
    macos = text[text.index("  on_macos do") : text.index("  on_linux do")]
    assert 'resource "macos-only"' in macos
    assert "    resource" in macos
    digest = hashlib.sha256(b"idna").hexdigest()
    assert (
        '  resource "idna" do\n'
        '    url "https://files.pythonhosted.org/packages/xx/idna-3.10.tar.gz"\n'
        f'    sha256 "{digest}"\n'
        "  end\n"
    ) in text
    assert text.endswith("  end\nend\n")
    assert "\n\n\n" not in text
    assert _render() == text  # deterministic


def test_no_platform_blocks_when_every_dependency_is_shared() -> None:
    text = _render(
        python="3.14", lock=_lock(LOCK.replace("sys_platform == 'darwin'", "os_name == 'posix'"))
    )
    assert "on_macos" not in text


@pytest.mark.parametrize(
    ("marker", "expected"),
    [
        ("sys_platform == 'darwin'", True),
        ("sys_platform != 'darwin'", False),
        ("python_full_version >= '3.14'", True),
        ("python_version < '3.14.1'", True),
        ("python_version > '3.9'", True),
        ("python_version <= '3.13'", False),
        ("(sys_platform == 'win32' or sys_platform == 'darwin') and os_name == 'posix'", True),
        ("sys_platform == 'win32' or extra == 'x'", False),
        ("'darwin' == sys_platform", True),
        ("sys_platform in 'darwin linux'", True),
        ("sys_platform not in 'win32 cygwin'", True),
        ("platform_python_implementation != 'PyPy'", True),
    ],
)
def test_evaluate(marker: str, expected: bool) -> None:
    assert brew.evaluate(marker, brew.environments("3.14")["macos"]) is expected


@pytest.mark.parametrize(
    "marker",
    [
        "platform_machine == 'arm64'",  # not set: never guessed
        "sys_platform == 'darwin' and",
        "(sys_platform == 'darwin'",
        "sys_platform == 'darwin' )",
        "sys_platform ~= 'x'",
        "sys_platform < 'x'",
        "python_version >= 'abc'",
    ],
)
def test_evaluate_refuses_what_it_cannot_read(marker: str) -> None:
    with pytest.raises(brew.FormulaError):
        brew.evaluate(marker, brew.environments("3.14")["macos"])


def test_refuses_a_lock_for_another_version() -> None:
    with pytest.raises(brew.FormulaError, match="run uv lock"):
        _render(version="1.3.0")


def test_refuses_a_dependency_without_an_sdist() -> None:
    lock = _lock(LOCK.replace(_pkg("idna", "3.10"), _pkg("idna", "3.10", sdist=False)))
    with pytest.raises(brew.FormulaError, match="idna has no sdist"):
        _render(lock=lock)


def test_refuses_an_ambiguous_or_missing_package() -> None:
    with pytest.raises(brew.FormulaError, match="several versions"):
        _render(lock=_lock(LOCK + _pkg("idna", "3.11")))
    with pytest.raises(brew.FormulaError, match=r"not in uv\.lock"):
        _render(lock=_lock(LOCK.replace(_pkg("idna", "3.10"), "")))


def test_picks_the_locked_version_a_dependency_names() -> None:
    text = LOCK.replace('{ name = "idna" }', '{ name = "idna", version = "3.11" }')
    assert "idna-3.11.tar.gz" in _render(lock=_lock(text + _pkg("idna", "3.11")))


@pytest.mark.parametrize(
    ("kw", "match"),
    [({"sdist_sha256": "XYZ"}, "SHA-256"), ({"python": "3"}, "--python")],
)
def test_refuses_bad_arguments(kw: dict[str, Any], match: str) -> None:
    with pytest.raises(brew.FormulaError, match=match):
        _render(**kw)


def test_refuses_a_bad_sdist_hash_or_url() -> None:
    digest = hashlib.sha256(b"idna").hexdigest()
    md5 = LOCK.replace(f"sha256:{digest}", "md5:abc")
    with pytest.raises(brew.FormulaError, match="no SHA-256"):
        _render(lock=_lock(md5))
    http = LOCK.replace("https://files.pythonhosted.org/packages/xx/idna", "http://x/idna")
    with pytest.raises(brew.FormulaError, match="not https"):
        _render(lock=_lock(http))


# The checkout's own lock: every runtime pin `uv export --no-dev` lists, except the Windows-only
# colorama, becomes a resource; no dev tool does.
def test_real_lock() -> None:
    lock = tomllib.loads((REPO / "uv.lock").read_text("utf-8"))
    version = tomllib.loads((REPO / "pyproject.toml").read_text("utf-8"))["project"]["version"]
    text = brew.render(
        lock, version=version, sdist_url=brew.sdist_url(version), sdist_sha256=SHA, python="3.14"
    )
    names = set(_resources(text))
    assert {"httpx", "pyperclip", "textual", "tomli-w", "typer", "rich", "pygments"} <= names
    assert names.isdisjoint({"colorama", "pytest", "ruff", "mypy", "promptmend"})


def _project(tmp_path: Path, version: str = "1.2.0") -> list[str]:
    (tmp_path / "pyproject.toml").write_text(f'[project]\nversion = "{version}"\n', "utf-8")
    (tmp_path / "uv.lock").write_text(LOCK, "utf-8")
    return ["--lock", str(tmp_path / "uv.lock"), "--pyproject", str(tmp_path / "pyproject.toml")]


def test_main_hashes_the_sdist_and_writes_the_formula(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    sdist = tmp_path / "promptmend-1.2.0.tar.gz"
    sdist.write_bytes(b"released sdist")
    out = tmp_path / "Formula" / "prompt-workflow.rb"
    out.parent.mkdir()
    assert brew.main([*_project(tmp_path), "--sdist", str(sdist), "-o", str(out)]) == 0
    assert f'sha256 "{hashlib.sha256(b"released sdist").hexdigest()}"' in out.read_text("utf-8")
    assert "Wrote" in capsys.readouterr().err


def test_main_prints_to_stdout(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    assert brew.main([*_project(tmp_path), "--sha256", SHA]) == 0
    assert capsys.readouterr().out == _render()


def test_main_refuses_the_sdist_of_another_version(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    sdist = tmp_path / "promptmend-1.1.0.tar.gz"
    sdist.write_bytes(b"x")
    assert brew.main([*_project(tmp_path), "--sdist", str(sdist)]) == 1
    assert "check out v1.2.0" in capsys.readouterr().err


def test_main_reports_a_missing_file(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    args = [*_project(tmp_path), "--sha256", SHA, "--lock", str(tmp_path / "nope.lock")]
    assert brew.main(args) == 1
    assert capsys.readouterr().err.startswith("brew_formula: ")
