"""scripts/release_notes.py and the release checks in scripts/check_wheel.py (offline)."""

import importlib.util
import shutil
import subprocess
import sys
import tomllib
from datetime import date
from pathlib import Path
from types import ModuleType

import pytest

REPO = Path(__file__).resolve().parents[1]


def _load(name: str) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, REPO / "scripts" / f"{name}.py")
    assert spec
    assert spec.loader
    module = importlib.util.module_from_spec(spec)
    # @dataclass resolves annotations through sys.modules, so register before executing.
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


notes = _load("release_notes")
check_wheel = _load("check_wheel")

GOOD = """# Changelog

Intro.

## Unreleased

### Added
- Next thing.

## 1.2.0 - 2026-10-04

Upgrading: read this.

### Fixed
- A bug.

## 1.1.0 - 2026-10-04

- Same-day release.

## 1.0.0 - 2026-09-01

First release.
"""


# The release workflow tags the pyproject version with the notes of its CHANGELOG section, so
# the newest section must be that version, dated (#28).
def test_changelog_newest_version_is_the_pyproject_version():
    pyproject = tomllib.loads((REPO / "pyproject.toml").read_text("utf-8"))
    changelog = (REPO / "CHANGELOG.md").read_text("utf-8")
    release = notes.current(changelog, pyproject["project"]["version"])
    assert release.notes


def test_every_changelog_version_is_dated():
    found = notes.releases((REPO / "CHANGELOG.md").read_text("utf-8"))
    assert "0.10.0" in [r.version for r in found]
    assert all(isinstance(r.date, date) for r in found)


def test_releases_parses_sections():
    found = notes.releases(GOOD)
    assert [r.version for r in found] == ["1.2.0", "1.1.0", "1.0.0"]
    assert found[0].date == date(2026, 10, 4)
    assert found[0].notes == "Upgrading: read this.\n\n### Fixed\n- A bug."
    assert found[2].notes == "First release."


@pytest.mark.parametrize(
    ("text", "error"),
    [
        ("## 1.0.0\n\n- x\n", "is not 'X.Y.Z - YYYY-MM-DD'"),
        ("## 1.0.0 — first\n\n- x\n", "is not 'X.Y.Z - YYYY-MM-DD'"),
        ("## 1.0.0 - 2026-13-01\n\n- x\n", "invalid date"),
        ("## 1.0.0 - 2026-10-01\n\n- x\n\n## Unreleased\n\n- y\n", "'Unreleased'"),
        ("## 1.0.0 - 2026-10-01\n\n- x\n\n## 1.1.0 - 2026-09-01\n\n- y\n", "listed after"),
        ("## 1.0.0 - 2026-10-01\n\n- x\n\n## 1.0.0 - 2026-09-01\n\n- y\n", "listed after"),
        ("## 1.1.0 - 2026-09-01\n\n- x\n\n## 1.0.0 - 2026-10-01\n\n- y\n", "dated after"),
        ("## 1.0.0 - 2026-10-01\n\n## 0.9.0 - 2026-09-01\n\n- y\n", "1.0.0 has no notes"),
        ("## Unreleased\n\n- x\n", "no released version"),
    ],
)
def test_releases_rejects(text, error):
    with pytest.raises(ValueError, match=error):
        notes.releases(text)


def test_current_requires_the_newest_version():
    assert notes.current(GOOD, "1.2.0").version == "1.2.0"
    with pytest.raises(
        ValueError, match=r"newest CHANGELOG version is 1\.2\.0, pyproject has 1\.3"
    ):
        notes.current(GOOD, "1.3.0")


def _project(tmp_path, version="1.2.0"):
    (tmp_path / "CHANGELOG.md").write_text(GOOD, encoding="utf-8")
    (tmp_path / "pyproject.toml").write_text(
        f'[project]\nname = "x"\nversion = "{version}"\n', encoding="utf-8"
    )
    return [
        "--changelog",
        str(tmp_path / "CHANGELOG.md"),
        "--pyproject",
        str(tmp_path / "pyproject.toml"),
    ]


def test_main_prints_version_and_notes(tmp_path, capsys):
    args = _project(tmp_path)
    notes.main(["version", *args])
    assert capsys.readouterr().out == "1.2.0"
    notes.main(["notes", *args])
    assert capsys.readouterr().out == "Upgrading: read this.\n\n### Fixed\n- A bug.\n"


def test_main_fails_on_a_mismatch(tmp_path):
    with pytest.raises(SystemExit, match="release_notes: the newest CHANGELOG version"):
        notes.main(["version", *_project(tmp_path, "2.0.0")])


CONSTRAINTS = """# This file was autogenerated by uv via the following command:
#    uv export --frozen --no-dev --no-emit-project --no-hashes
colorama==0.4.6 ; sys_platform == 'win32'
    # via typer
typing-extensions==4.16.0 ; python_full_version < '3.13'
    # via anyio
httpx==0.28.1
    # via espanso-prompt-rewriter
"""


def test_constraints_match_the_installed_versions():
    # Name normalisation; a marker-excluded pin (colorama off Windows) has nothing to compare.
    installed = {"HTTPX": "0.28.1", "typing_extensions": "4.16.0"}
    assert check_wheel.constraint_mismatches(CONSTRAINTS, installed) == []


def test_constraints_report_drift_and_unpinned():
    installed = {"httpx": "0.28.2", "rich": "15.0.0"}
    assert check_wheel.constraint_mismatches(CONSTRAINTS, installed) == [
        "httpx 0.28.2 (constraints: 0.28.1)",
        "rich 15.0.0 (constraints: not pinned)",
    ]


def test_constraints_reject_an_unpinned_line():
    with pytest.raises(ValueError, match="not name==version"):
        check_wheel.constraint_mismatches("httpx>=0.27\n", {})


# The release's constraints.txt is the workflow's `uv export` of uv.lock: every pin is the
# locked version, and every locked runtime dependency is pinned.
def test_constraints_export_matches_the_lock():
    uv = shutil.which("uv")
    if uv is None:
        pytest.skip("uv not on PATH")
    export = subprocess.run(
        [uv, "export", "--frozen", "--offline", "--no-dev", "--no-emit-project", "--no-hashes"],
        cwd=REPO, capture_output=True, text=True, check=True, timeout=60,
    )  # fmt: skip
    lock = tomllib.loads((REPO / "uv.lock").read_text("utf-8"))
    locked = {p["name"]: p["version"] for p in lock["package"] if "version" in p}
    pinned = [
        line.split(";")[0].strip().split("==")
        for line in export.stdout.splitlines()
        if line and not line.startswith((" ", "#"))
    ]
    assert {"httpx", "pyperclip", "typer"} <= {name for name, _ in pinned}
    assert "espanso-prompt-rewriter" not in {name for name, _ in pinned}
    assert check_wheel.constraint_mismatches(export.stdout, dict(pinned)) == []
    assert all(locked[name] == version for name, version in pinned)
