import ctypes
import os
import sys
import time
from collections.abc import Sequence
from types import SimpleNamespace
from typing import Any

import pytest

from promptmend import clipboard_guard
from promptmend.clipboard_guard import is_concealed, mac_concealed, win_concealed

# The marker names are spelled out here, not taken from the module, so a test cannot simply
# mirror a wrong or missing name.


class _FakeObjC:
    """An Objective-C runtime whose general pasteboard holds the given types."""

    def __init__(self, types: list[str] | None) -> None:
        self.types = types

    def cls(self, name: str) -> object:
        return name

    def call(self, obj: object, selector: str, *args: int) -> Any:
        if (obj, selector) == ("NSPasteboard", "generalPasteboard"):
            return "general"
        if (obj, selector) == ("general", "types"):
            return None if self.types is None else "types"
        assert self.types is not None
        if selector == "count":
            return len(self.types)
        assert selector == "objectAtIndex:"
        return self.types[args[0]]

    def string(self, obj: object) -> str:
        assert isinstance(obj, str)
        return obj


# macOS: an item is concealed when any of its types is a password-manager marker.
@pytest.mark.parametrize(
    ("types", "concealed"),
    [
        (["public.utf8-plain-text"], False),
        (["public.utf8-plain-text", "org.nspasteboard.ConcealedType"], True),
        (["org.nspasteboard.TransientType"], False),  # a text expander's momentary paste
        (["public.utf8-plain-text", "com.agilebits.onepassword"], True),
        (["org.nspasteboard.AutoGeneratedType"], False),
        ([], False),
        (None, False),  # an empty pasteboard has no types array
    ],
    ids=["plain", "concealed", "transient", "onepassword", "auto-generated", "no-types", "nil"],
)
def test_mac_concealed(types: list[str] | None, concealed: bool) -> None:
    assert mac_concealed(_FakeObjC(types)) is concealed


class _FakeClipboard:
    """A Windows clipboard holding the given formats; DWORD formats map to their value."""

    def __init__(self, formats: dict[str, int | None]) -> None:
        self.formats = formats

    def has_format(self, name: str) -> bool:
        return name in self.formats

    def read_dword(self, name: str) -> int | None:
        return self.formats[name]


# Windows: a do-not-read format, or a history opt-out (DWORD 0), marks the item.
@pytest.mark.parametrize(
    ("formats", "concealed"),
    [
        ({}, False),
        ({"ExcludeClipboardContentFromMonitorProcessing": None}, True),
        ({"Clipboard Viewer Ignore": None}, True),
        ({"CanIncludeInClipboardHistory": 0}, True),
        ({"CanIncludeInClipboardHistory": 1}, False),
        # Bitwarden sets only this format; present but unreadable still counts.
        ({"CanIncludeInClipboardHistory": None}, True),
    ],
    ids=["plain", "exclude-monitor", "viewer-ignore", "no-history", "history-ok", "busy"],
)
def test_win_concealed(formats: dict[str, int | None], concealed: bool) -> None:
    assert win_concealed(_FakeClipboard(formats)) is concealed


# Every OS dispatches to its own probe; one without a probe cannot tell.
def test_is_concealed_dispatch(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setitem(clipboard_guard._PROBES, "darwin", lambda: True)
    monkeypatch.setitem(clipboard_guard._PROBES, "win32", lambda: False)
    assert is_concealed("darwin") is True
    assert is_concealed("win32") is False
    assert is_concealed("linux") is None


# A probe that fails (a missing library, a ctypes error) cannot tell either: fail open.
@pytest.mark.parametrize(
    "error", [OSError, AttributeError, ValueError, TypeError, ctypes.ArgumentError, RuntimeError]
)
def test_is_concealed_fails_open(monkeypatch: pytest.MonkeyPatch, error: type[Exception]) -> None:
    def broken() -> None:
        raise error("no clipboard")

    monkeypatch.setitem(clipboard_guard._PROBES, sys.platform, broken)
    assert is_concealed() is None


# The ctypes wrappers fail cleanly on the wrong OS, which is_concealed() turns into None.
@pytest.mark.skipif(sys.platform == "win32", reason="user32 exists on Windows")
def test_windows_probe_is_none_elsewhere() -> None:
    assert is_concealed("win32") is None


@pytest.mark.skipif(sys.platform == "darwin", reason="AppKit exists on macOS")
def test_mac_probe_is_none_elsewhere() -> None:
    assert is_concealed("darwin") is None


@pytest.mark.skipif(sys.platform != "darwin", reason="needs the macOS pasteboard")
def test_mac_probe_on_a_real_pasteboard() -> None:
    """Write items to a private pasteboard (never the user's clipboard) and probe it through
    the real Objective-C runtime."""
    runtime = clipboard_guard._MacRuntime()
    buffers: list[ctypes.Array[ctypes.c_char]] = []

    def nsstring(text: str) -> Any:
        buffers.append(ctypes.create_string_buffer(text.encode()))
        address = ctypes.addressof(buffers[-1])
        return runtime.call(runtime.cls("NSString"), "stringWithUTF8String:", address)

    pasteboard = runtime.call(runtime.cls("NSPasteboard"), "pasteboardWithUniqueName")
    try:
        runtime.call(pasteboard, "clearContents")
        runtime.call(
            pasteboard, "setString:forType:", nsstring("draft"), nsstring("public.utf8-plain-text")
        )
        assert mac_concealed(runtime, pasteboard) is False
        for marker in ("org.nspasteboard.ConcealedType", "com.agilebits.onepassword"):
            runtime.call(pasteboard, "clearContents")
            runtime.call(pasteboard, "setString:forType:", nsstring("pw"), nsstring(marker))
            assert mac_concealed(runtime, pasteboard) is True
        runtime.call(pasteboard, "clearContents")
        transient = nsstring("org.nspasteboard.TransientType")
        runtime.call(pasteboard, "setString:forType:", nsstring("snippet"), transient)
        assert mac_concealed(runtime, pasteboard) is False
    finally:
        runtime.call(pasteboard, "releaseGlobally")


# On the two supported OSes the real probe answers, quickly: it runs before every expansion.
@pytest.mark.skipif(sys.platform not in ("darwin", "win32"), reason="no probe on this OS")
def test_real_probe_answers_quickly() -> None:
    started = time.perf_counter()
    assert is_concealed() is not None
    assert time.perf_counter() - started < 0.5


def _win_clipboard(
    opened: bool | list[bool] = True,
    handle: int | None = 1,
    pointer: int | None = None,
    formats: Sequence[str] = (),
    size: int = 4,
) -> tuple[clipboard_guard._WinClipboard, list[str]]:
    """A _WinClipboard over fake user32/kernel32 functions, so its logic runs on any OS.
    ``opened`` is a bool, or a list of OpenClipboard results in order."""
    calls: list[str] = []
    opens = list(opened) if isinstance(opened, list) else None
    clipboard = clipboard_guard._WinClipboard.__new__(clipboard_guard._WinClipboard)
    ids = {name: i for i, name in enumerate(formats, 0xC000)}

    def open_clipboard(owner: object) -> bool:
        if opens:
            calls.append("open")
            return opens.pop(0)
        return bool(opened)

    clipboard._user32 = SimpleNamespace(
        RegisterClipboardFormatW=lambda name: ids.get(name, 0xC100),
        IsClipboardFormatAvailable=lambda fmt: fmt in ids.values(),
        OpenClipboard=open_clipboard,
        GetClipboardData=lambda fmt: handle,
        CloseClipboard=lambda: calls.append("close"),
    )
    clipboard._kernel32 = SimpleNamespace(
        GlobalSize=lambda h: size,
        GlobalLock=lambda h: pointer,
        GlobalUnlock=lambda h: calls.append("unlock"),
    )
    return clipboard, calls


# The DWORD is read under a lock that is always released, and the clipboard always closed.
def test_win_read_dword() -> None:
    value = ctypes.c_uint32(0)
    clipboard, calls = _win_clipboard(pointer=ctypes.addressof(value))
    assert clipboard.read_dword("CanIncludeInClipboardHistory") == 0
    assert calls == ["unlock", "close"]


# A clipboard another app keeps holding, a format without data, or data too small for a
# DWORD cannot tell.
@pytest.mark.parametrize(
    ("opened", "handle", "size", "closes"),
    [
        (False, 1, 4, []),
        (True, None, 4, ["close"]),
        (True, 1, 4, ["close"]),
        (True, 1, 2, ["close"]),
    ],
    ids=["held", "no-data", "no-lock", "too-small"],
)
def test_win_read_dword_unavailable(
    monkeypatch: pytest.MonkeyPatch,
    opened: bool,
    handle: int | None,
    size: int,
    closes: list[str],
) -> None:
    monkeypatch.setattr(clipboard_guard, "OPEN_RETRY_SECONDS", 0)
    clipboard, calls = _win_clipboard(opened=opened, handle=handle, pointer=None, size=size)
    assert clipboard.read_dword("CanIncludeInClipboardHistory") is None
    assert calls == closes


# Data smaller than a DWORD is never read past its end.
def test_win_read_dword_too_small() -> None:
    value = ctypes.c_uint32(0)
    clipboard, _ = _win_clipboard(pointer=ctypes.addressof(value), size=2)
    assert clipboard.read_dword("CanIncludeInClipboardHistory") is None


# A clipboard held for a moment is retried, as pyperclip does, before giving up.
def test_win_read_dword_retries_open(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(clipboard_guard, "OPEN_RETRY_SECONDS", 0)
    value = ctypes.c_uint32(1)
    clipboard, calls = _win_clipboard(opened=[False, False, True], pointer=ctypes.addressof(value))
    assert clipboard.read_dword("CanIncludeInClipboardHistory") == 1
    assert calls == ["open", "open", "open", "unlock", "close"]


def test_win_has_format() -> None:
    clipboard, _ = _win_clipboard(formats=["ExcludeClipboardContentFromMonitorProcessing"])
    assert clipboard.has_format("ExcludeClipboardContentFromMonitorProcessing") is True
    assert clipboard.has_format("Clipboard Viewer Ignore") is False


@pytest.mark.skipif(
    sys.platform != "win32" or not os.environ.get("CI"),
    reason="writes the real Windows clipboard, so it runs only on CI",
)
@pytest.mark.parametrize(
    ("name", "value", "concealed"),
    [
        ("ExcludeClipboardContentFromMonitorProcessing", 1, True),
        ("Clipboard Viewer Ignore", 1, True),
        ("CanIncludeInClipboardHistory", 0, True),
        ("CanIncludeInClipboardHistory", 1, False),
        (None, 0, False),
    ],
    ids=["exclude-monitor", "viewer-ignore", "no-history", "history-ok", "plain"],
)
def test_windows_probe_on_the_real_clipboard(name: str | None, value: int, concealed: bool) -> None:
    win_dll = getattr(ctypes, "WinDLL")  # noqa: B009 - absent from ctypes off Windows
    user32, kernel32 = win_dll("user32"), win_dll("kernel32")
    kernel32.GlobalAlloc.restype = ctypes.c_void_p
    kernel32.GlobalAlloc.argtypes = [ctypes.c_uint, ctypes.c_size_t]
    kernel32.GlobalLock.restype = ctypes.c_void_p
    kernel32.GlobalLock.argtypes = [ctypes.c_void_p]
    kernel32.GlobalUnlock.argtypes = [ctypes.c_void_p]
    user32.SetClipboardData.restype = ctypes.c_void_p
    user32.SetClipboardData.argtypes = [ctypes.c_uint, ctypes.c_void_p]
    user32.RegisterClipboardFormatW.restype = ctypes.c_uint
    user32.RegisterClipboardFormatW.argtypes = [ctypes.c_wchar_p]
    for _ in range(20):
        if user32.OpenClipboard(None):
            break
        time.sleep(0.05)
    else:
        pytest.fail("the clipboard stayed held by another app")
    try:
        user32.EmptyClipboard()
        if name:
            data = kernel32.GlobalAlloc(0x0002, 4)  # GMEM_MOVEABLE, one DWORD
            ctypes.c_uint32.from_address(kernel32.GlobalLock(data)).value = value
            kernel32.GlobalUnlock(data)
            assert user32.SetClipboardData(user32.RegisterClipboardFormatW(name), data)
    finally:
        user32.CloseClipboard()
    assert is_concealed() is concealed
