"""SHA-256 of every espanso/match/ source a release shipped, plus the current one.

Generated by scripts/update_match_history.py; do not edit by hand.
"""

KNOWN_SOURCES: dict[str, frozenset[str]] = {
    "base.yml": frozenset(
        {
            "794bd248b8910e58192b543861d4e3e1b23b8de8b58772f52040e2e733554c96",
        }
    ),
    "prompts-core.yml": frozenset(
        {
            "0c0e2c0bf68a4e2573c713470c5cd4d43451e76691c8e671ae066944f807bbc4",
            "1c354d11cb89460ad12a0539d025eeecaf94fd4c6b3a92393455d1670551cde4",
            "1cf316c0745bbdc9827643530caacf3b782a59cb72312ccfebcfccd4ea73c656",
            "7d04c4988a4bacf0b8e43bba5182886020b9bddd3d7fe41846390b46caec3170",
        }
    ),
    "prompts-llm.yml": frozenset(
        {
            "2e120ea22d5791f4f9666d39d59aace143f8f50777bdb1f94246a2b07ac1085f",
            "2f4a39feed880856a5f11ac5ae4a37a7ff690a88a07a3afc58b3556d9aedfa09",
            "4ffb6b04f406e81bae125a8d6fdcdad6ce1022f4b086697b236526469c51e8d1",
            "591c2fc3e1d65ab9288957e04eca1e1919f56814c0ad71512991b4a3d192a077",
            "8ae1421a528c7fded5459e46bdf92838ce6ec6686b3f5b9a191226ed76dae082",
            "8f9eb7a8d4cd42606df54f7e3e3ea7cdcfd9e57770dbd39fc6ed020bc3d3d21c",
            "9454bff8830e3ab38934a0f1a97cb42fdad6769cc0249cce38a456dc1dfe796c",
            "9bc66c69044c3b795126cb5819f70dce11435f7167bf6ad1fdc94d0614b02c4e",
            "c8f51c448713aff6f0ea69a83d6a9e1e918b28569bf1430597e675cf0f59a2da",
            "e7e437e9e07e78de55f181d8f263f31dbe06bc3617defca8b2665bbed548ed77",
        }
    ),
    "prompts-template.yml": frozenset(
        {
            "1b967f502089e307a885ba7b3eb3a85782629c443bc4bc50ac864364b1c0e0ad",
            "1d271379279e787f18b1515d1c13990e718efad3ea562f78dd8a14d8640a3a4e",
            "38045846defcbbcf355e4fcf0db551516a141a02f7a483fba6876e417b8e15cc",
            "53292b9f1d1c24e3771606b69c7c6bff9feacca9395b9668e36d6762752ad1b1",
            "5b3b9f2541e3dafebd033c724febb77b8e9a4478d17f3deaad364a5195e85153",
            "882c8d4ac9943da4243cbf5205bc1c559ae558080fa83c3786aae72fcad82dc5",
            "979d901048cb560a1dae2017e4551590a46aa815b0f7a2b8a8a3d5f9347d985c",
            "a064a91c8e05437d00e3b708434d492d1e6903eba912b9bf19488b97d46a648b",
            "b5715354600d86b6ff4b5369586479ded87da27d8c4fbbe6ec3c296503d91e46",
            "cfddea43ae7e5dba1518a0c585fae4cacf5867da2cac1877c6b70e2c211dc695",
        }
    ),
}
