"""Regenerate src/prompt_workflow/match_history.py: the SHA-256 of every espanso/match/ source
anyone could have deployed. That is the union of
- every digest the module already lists (a digest is never dropped),
- each `v*` tag's version of each file,
- the file at every commit that changed it on this branch and on the default branch
  (origin/HEAD), since an editable install runs an untagged commit,
- the checkout's current files.

deploy.py uses it to recognise a match file an older install script wrote (no stamp, no
manifest) as ours and stale instead of foreign. Run at every release, after tagging, and
whenever a match file changes:

    uv run python scripts/update_match_history.py

tests/test_deploy.py fails when the module misses a tagged or the current source.
"""

from __future__ import annotations

import hashlib
import importlib.util
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MATCH = Path("espanso") / "match"
MODULE = REPO / "src" / "prompt_workflow" / "match_history.py"


def _git(*args: str) -> str:
    return subprocess.run(  # noqa: S603 - fixed argv, no shell
        ["git", *args],  # noqa: S607
        cwd=REPO,
        capture_output=True,
        text=True,
        encoding="utf-8",
        timeout=30,
        check=True,
    ).stdout


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def tagged_digests() -> dict[str, set[str]]:
    """Digest of each match file in each release tag that has it."""
    found: dict[str, set[str]] = {}
    for tag in _git("tag", "--list", "v*").split():
        for path in _git("ls-tree", "--name-only", f"{tag}:{MATCH.as_posix()}").split():
            if path.endswith(".yml"):
                text = _git("show", f"{tag}:{(MATCH / path).as_posix()}")
                found.setdefault(path, set()).add(digest(text))
    return found


def _refs() -> list[str]:
    """This branch and, when the clone knows it, the default branch."""
    refs = ["HEAD"]
    found = subprocess.run(
        ["git", "rev-parse", "--verify", "--quiet", "origin/HEAD"],  # noqa: S607
        cwd=REPO,
        capture_output=True,
        timeout=30,
        check=False,
    )
    if found.returncode == 0:
        refs.append("origin/HEAD")
    return refs


def history_digests() -> dict[str, set[str]]:
    """Digest of each match file at every commit that changed espanso/match/, on this branch
    and the default branch. Each distinct blob is read once."""
    blobs: dict[str, set[str]] = {}
    commits = _git("log", "--format=%H", *_refs(), "--", MATCH.as_posix()).split()
    for commit in dict.fromkeys(commits):
        for line in _git("ls-tree", commit, f"{MATCH.as_posix()}/").splitlines():
            meta, _, path = line.partition("\t")
            name = Path(path).name
            if meta.split()[1] == "blob" and name.endswith(".yml"):
                blobs.setdefault(meta.split()[2], set()).add(name)
    found: dict[str, set[str]] = {}
    for blob, names in blobs.items():
        text = _git("cat-file", "blob", blob)
        for name in names:
            found.setdefault(name, set()).add(digest(text))
    return found


def listed_digests() -> dict[str, set[str]]:
    """What match_history.py lists now; {} when it does not exist yet."""
    if not MODULE.exists():
        return {}
    spec = importlib.util.spec_from_file_location("_listed_match_history", MODULE)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {MODULE}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return {name: set(found) for name, found in module.KNOWN_SOURCES.items()}


def current_digests() -> dict[str, set[str]]:
    return {
        p.name: {digest(p.read_bytes().decode("utf-8"))}
        for p in sorted((REPO / MATCH).glob("*.yml"))
    }


def render_module(digests: dict[str, set[str]]) -> str:
    lines = [
        '"""SHA-256 of every espanso/match/ source a release shipped, plus the current one.',
        "",
        "Generated by scripts/update_match_history.py; do not edit by hand.",
        '"""',
        "",
        "KNOWN_SOURCES: dict[str, frozenset[str]] = {",
    ]
    for name in sorted(digests):
        lines.append(f'    "{name}": frozenset(')
        lines.append("        {")
        lines.extend(f'            "{d}",' for d in sorted(digests[name]))
        lines.append("        }")
        lines.append("    ),")
    lines.append("}")
    return "\n".join(lines) + "\n"


def collect() -> dict[str, set[str]]:
    merged: dict[str, set[str]] = {}
    for source in (listed_digests(), tagged_digests(), history_digests(), current_digests()):
        for name, found in source.items():
            merged.setdefault(name, set()).update(found)
    return merged


def main() -> int:
    MODULE.write_bytes(render_module(collect()).encode("utf-8"))
    print(f"wrote {MODULE.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
